name: "Build and deploy"

on:
  push:
    branches:
      #####################################
      # Add branches to deploy from here. #
      #####################################
      - production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: "20.16"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: "Install node-modules"
        shell: sh
        run: |
          npm ci

      - name: "Build site"
        shell: sh
        run: |
          npm run build

      - name: "Remove extraneous files"
        run: |
          npm prune --production

      - name: "Upload static files as artifact"
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: "Deploy to GitHub pages"
        id: deployment
        uses: actions/deploy-pages@v4
